#!/usr/bin/env python3
"""
Fetch daily port activity data from IMF PortWatch API and generate a SQL migration
that replaces synthetic historical_demand data with real data.
"""

import json
import urllib.request
import urllib.parse
from datetime import datetime, date
from pathlib import Path

BASE_URL = "https://services9.arcgis.com/weJ1QsnbMYJlCHdG/arcgis/rest/services/Daily_Ports_Data/FeatureServer/0/query"

# IMF portid -> our DB port code
PORT_MAP = {
    "port1188": "CNSHA",
    "port1114": "NLRTM",
    "port1201": "SGSIN",
    "port908":  "GRPIR",
    "port446":  "DEHAM",
    "port1348": "ESVLC",
    "port518":  "SAJED",
    "port744":  "AEJEA",
    "port776":  "INNSA",
    "port664":  "USLAX",
    "port1160": "BRSSZ",
    "port31":   "ESALG",
    "port1265": "MAPTM",
    "port254":  "LKCMB",
    "port215":  "ZACPT",
}

# Trade lane definitions: (lane_name, origin_imf_portid, origin_code, dest_code, metric_field)
# We use export_container from the origin port as the basis for TEU volume
TRADE_LANES = [
    ("ASIA-EUROPE",       "port1188", "CNSHA", "NLRTM", "export_container"),
    ("EUROPE-AMERICAS",   "port1114", "NLRTM", "USLAX", "export_container"),
    ("GULF-EUROPE",       "port744",  "AEJEA", "NLRTM", "export_container"),
    ("INTRA-ASIA",        "port1188", "CNSHA", "SGSIN", "export_container"),
    ("MED-NORTHEUROPE",   "port908",  "GRPIR", "NLRTM", "export_container"),
    ("INDIA-GULF",        "port776",  "INNSA", "AEJEA", "export_container"),
]

DATE_START = "2025-04-01"
DATE_END = "2026-03-31"


def fetch_port_data(imf_portid: str) -> dict:
    """Fetch daily data for a port from IMF PortWatch API. Returns {date_str: record}."""
    params = {
        "where": f"portid='{imf_portid}' AND date >= '{DATE_START}' AND date <= '{DATE_END}'",
        "outFields": "date,portcalls_container,portcalls,import_container,export_container",
        "f": "json",
        "resultRecordCount": "2000",
        "orderByFields": "date ASC",
    }
    url = BASE_URL + "?" + urllib.parse.urlencode(params)
    print(f"  Fetching {imf_portid} ...")

    req = urllib.request.Request(url)
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.loads(resp.read().decode())

    if "features" not in data:
        print(f"  WARNING: No features in response for {imf_portid}")
        print(f"  Response keys: {list(data.keys())}")
        return {}

    results = {}
    for feat in data["features"]:
        attrs = feat["attributes"]
        dt = attrs.get("date")
        if dt is None:
            continue
        # date may be a string "YYYY-MM-DD" or epoch millis
        if isinstance(dt, (int, float)):
            dt = datetime.utcfromtimestamp(dt / 1000).strftime("%Y-%m-%d")
        else:
            dt = str(dt).strip()[:10]  # ensure "YYYY-MM-DD"
        results[dt] = attrs

    print(f"  Got {len(results)} days for {imf_portid}")
    return results


def generate_sql(all_port_data: dict) -> str:
    """Generate SQL migration from fetched data."""
    lines = []
    lines.append("-- V4__real_imf_data.sql")
    lines.append("-- Replace synthetic historical_demand with real IMF PortWatch data")
    lines.append("-- Generated by scripts/import_imf_data.py")
    lines.append(f"-- Data period: {DATE_START} to {DATE_END}")
    lines.append("")
    lines.append("-- Clear existing synthetic data")
    lines.append("DELETE FROM historical_demand;")
    lines.append("")

    total_rows = 0

    for lane_name, imf_portid, origin_code, dest_code, metric_field in TRADE_LANES:
        port_data = all_port_data.get(imf_portid, {})
        if not port_data:
            lines.append(f"-- WARNING: No data for {lane_name} ({imf_portid})")
            lines.append("")
            continue

        lines.append(f"-- {lane_name}: {origin_code} -> {dest_code}")
        lines.append(f"INSERT INTO historical_demand (id, trade_lane, origin_port_id, destination_port_id, cargo_type, date, teu_volume, revenue, booking_count)")
        lines.append("VALUES")

        values = []
        # Generate date range and look up data
        current = date.fromisoformat(DATE_START)
        end = date.fromisoformat(DATE_END)

        while current <= end:
            date_str = current.isoformat()
            record = port_data.get(date_str)

            if record is not None:
                raw_metric = record.get(metric_field)
                if raw_metric is not None and raw_metric > 0:
                    # export_container is in metric tons; divide by 14 to approximate TEU
                    teu_volume = round(raw_metric / 14, 1)
                    revenue = round(teu_volume * 1500, 2)
                    booking_count = max(1, round(teu_volume / 20))

                    values.append(
                        f"  (uuid_generate_v4(), '{lane_name}', "
                        f"(SELECT id FROM ports WHERE code = '{origin_code}'), "
                        f"(SELECT id FROM ports WHERE code = '{dest_code}'), "
                        f"'MIXED_CONTAINER', '{date_str}', {teu_volume}, {revenue}, {booking_count})"
                    )

            current = date(current.year, current.month, current.day)
            # advance by one day
            from datetime import timedelta
            current += timedelta(days=1)

        if values:
            lines.append(",\n".join(values) + ";")
            total_rows += len(values)
            lines.append(f"-- {len(values)} rows for {lane_name}")
        else:
            # Remove the INSERT/VALUES lines if no data
            lines.pop()  # VALUES
            lines.pop()  # INSERT
            lines.append(f"-- WARNING: No valid {metric_field} data for {lane_name}")

        lines.append("")

    print(f"\nTotal rows to insert: {total_rows}")
    return "\n".join(lines)


def main():
    print("=== IMF PortWatch Data Import ===")
    print(f"Period: {DATE_START} to {DATE_END}\n")

    # Determine which ports we actually need
    needed_ports = set()
    for _, imf_portid, _, _, _ in TRADE_LANES:
        needed_ports.add(imf_portid)

    print(f"Fetching data for {len(needed_ports)} ports...")

    all_port_data = {}
    for imf_portid in sorted(needed_ports):
        try:
            all_port_data[imf_portid] = fetch_port_data(imf_portid)
        except Exception as e:
            print(f"  ERROR fetching {imf_portid}: {e}")
            all_port_data[imf_portid] = {}

    print("\nGenerating SQL...")
    sql = generate_sql(all_port_data)

    # Write output
    script_dir = Path(__file__).resolve().parent
    project_root = script_dir.parent
    output_path = project_root / "src" / "main" / "resources" / "db" / "migration" / "V4__real_imf_data.sql"

    output_path.write_text(sql, encoding="utf-8")
    print(f"\nWrote migration to: {output_path}")
    print("Done!")


if __name__ == "__main__":
    main()
